### ISSUE TITLE
Partner logos underneath CTA section 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/website#150]
## Description

As a user I want to see what organizations are supporting Alkemio
As a partner I want to see my logo on the site

## Acceptance criteria

Part 1
- [x] Partner logos visible under the main CTA section
- [x] Partner carousel responsive

**Comment by Roseghost** [comment]
Carousel coded:

![WhatsApp Image 2022-04-10 at 21.37.20.jpeg](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/7b1d6e7a-3a17-44ac-89a2-e940ba583c73)![WhatsApp Image 2022-04-10 at 21.38.30.jpeg](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/4725dba1-4ab0-4d72-a183-e2cd336bc4f8)

![responsive carousel.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/85c610bf-e804-4c68-a19a-b1062104b6ed)

Widget made for this and its responsive (yeey!)

**Comment by techsmyth** [comment]
Logos to show in Carousel: UWV, VNG, Digicampus, Min BZK, EU / NGI, KvK, SIDN Fonds, Odyssey
