### ISSUE TITLE
Demo video on website

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/website#233]
## Description
As a user
I want to easily access the Alkemio videos
So that I know what Alkemio is and how to use it

## Acceptance criteria

- [ ] English introduction video on website (see image below) 

## Introduction video 

**Location:** alkem.io 

**Video link:** `https://vimeo.com/708619604?utm_campaign=2022VIDEO&utm_source=VIDEO&utm_medium=VIMEO&utm_term=Click&utm_content=2022Video`

**Embed code:**  `<iframe title="vimeo-player" src="https://vimeo.com/708619604?utm_campaign=2022VIDEO&utm_source=VIDEO&utm_medium=VIMEO&utm_term=Click&utm_content=2022Video" width="640" height="360" frameborder="0" allowfullscreen></iframe> `

![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/aff3a248-945e-4287-89eb-6cdcc6fb325b)

**Comment by techsmyth** [comment]
@Fintokyo can you please have a look at where you think the video should go on the website?

**Comment by Fintokyo** [comment]
The location looks good; I'd suggest making the video image a bit smaller (around 20% smaller) so that there is a bit more space around it, as otherwise this top section looks a bit too busy.

**Comment by hoyterutteman** [comment]
I updated the screenshot according to Fintants feedback
