### ISSUE TITLE
Manifesto layout 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/website#308]
## Description

As a champion I want a great looking manifesto that is easy to follow

## Acceptance criteria
For the Manifesto page
- [x] The first block, the header should be Alkemio Manifesto. 
- [x] The block behind the cta button does not need a different background color. It can be in the same block as the header- idem for the manifesto header.  Make the button size smaller, to avoid it looking too sales focused on the manifesto page
(I know this differs from the webpage style but this makes it harder to start reading. )
- [x]  The font size/colour should be more consistent in the top section, currently each of the 5 lines (from Alkemio Manifesto to the cta button) are different sizes/colours/bolds and it is a bit disjointed.
- [x] The background of each image+text blocks should diverse in color (can be light differentiation, but needs to jump out more)
- [x] The blocks need to be serried (no space between them).  Keep space between the header and body text of each block
- [x] Make each photo/image smaller (as well as all being the same size)
(so it doesn't take as long to get to the bottom of the page, and also to better match the amount of space needed for the wording in each section; I think around 8cm height (on the desktop version) would be good (currently 9.5-11cm height))
- [x] The text in the second line in the bullet section should be aligned with the text above (see my comment to this issue)

To discuss: 
- alignment (left vs center) in top block
- For Lazar, in the image for 'Open for all', is it possible to have the two hands touching, I think that would convey the concept better

**Comment by hoyterutteman** [comment]
![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/29e69d9a-5041-4236-b10f-0777da21121a)

**Comment by hoyterutteman** [comment]
![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/3ca11d43-b780-4631-9f24-90e421fc25ad)

**Comment by BirgitAlkemio** [comment]
Above acceptance criteria are covered in another issue #312

**Comment by techsmyth** [comment]
Actually the issues do not get closed until either the work is done or the associated PR is merged - so as 312 is still open this issue should also be still open. However the two should be linked so that they show up as one - I have connected them via the PR.
