### ISSUE TITLE
Blogpost width

### ISSUE THREAD

**Issue by BirgitAlkemio** [alkem-io/website#341]
Blogpost bug/issue showing narrowed content blocks on its contentpage. 
![image.png](https://images.zenhubusercontent.com/627a603379f32b857065b7d2/7d1b8158-56b7-4f65-a706-076c1363a4d5)

**Comment by Roseghost** [comment]
Very unusual  - Technically has been fixed 2 weeks ago but doesn't seem to take effect on the live version. 

https://github.com/alkem-io/website/blob/develop/static/css/custom.css Article width should fix it. 
I suspect the {{.Site.BaseURL}} part in partials isnt working properly 
" <link rel="stylesheet" type="text/css" href="{{.Site.BaseURL}}css/custom.css" />"

**Comment by techsmyth** [comment]
@Roseghost if you need help can you please ping Rene to look at this with you @renehonig

**Comment by Roseghost** [comment]
@renehonig  Hi Rene, zou je hier met mij naar kunnen kijken als je tijd hebt? Ik krijg het niet opgelost helaas
