### ISSUE TITLE
Center align the menu

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/website#386]
## Description

As a user I want to see the platform link, which at the moment does not full visibility as the attention is on the left at the top

## Acceptance criteria

- [ ] Menu should be in the middle 

## Additional Context
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/f15c1764-dff5-4bd7-9120-fe39a8802490)

**Comment by BirgitAlkemio** [comment]
@techsmyth Could you explain what menu? The header text of the landing pages? If so, I would suggest not to do so. Look at other webpages, They are either left or right aligned , giving room to buttons or seach fields.

**Comment by Fintokyo** [comment]
I think it is okay to keep the left alignment so long as we can find a way to give a bit more balance to the menu; as currently my attention is completely drawn to the left of the menu and I don't really notice the 'Platform' button on the far right side. One way, based on looking at other websites (Shopify, Squareup) is to have multiple items on the right side, for example by also moving the 'About' tab to the right side of the menu beside the 'Platform' button. Then people's attention will be more drawn to both the left and the right sides of the menu bar. If we do this we may want to make the Platform button a bit smaller than it currently is, to avoid it being too much bigger than the About tab.
