### ISSUE TITLE
Community management help page

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/website#412]
## Description

As a usage lead I want to help all community managers with the basic steps to get their community active

## Acceptance criteria

- [ ] Page on website called "help/community-management" that is linked to from the help center
- [ ] Content to cover e.g. how to send updates, how to manage members, how to manage admins

## Additional Context
https://hackmd.io/UkIZnvLlT36XriDXm7FkVw

**Comment by techsmyth** [comment]
@larssondenise super document to have! Reads really nicely. I have made some updates to it as well - can you please convert it into a PR on the website repo so we can get this important document live?!

**Comment by hoyterutteman** [comment]
Reviewed and made some small additions. Really nice document!
