### ISSUE TITLE
Home page: users want to see challenges in action

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/website#435]
## Description

As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria

- [ ] Replace button at bottom of home page "Want to get started?" with a button "See Challenges in action!" that links to the platform home page.

**Comment by techsmyth** [comment]
@Fintokyo feedback...

**Comment by BirgitAlkemio** [comment]
https://github.com/alkem-io/website/pull/479
