### ISSUE TITLE
Team pictures

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/website#502]
## Description

As a new user I want to see the team

## Acceptance criteria

- [x] All profile picture to be black + white, and properly centered so that all faces have the same size
- [x] Board of advisors pictures reverted to what they were
- [x] Pictures shown for all past contributors

**Comment by Roseghost** [comment]
Closed with https://github.com/alkem-io/website/pull/513/commits/50689cc844daac94df35c2503a8268b85cb2e163
