### ISSUE TITLE
Foundation display on LinkedIn

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/website#739]
## Description

As a user sharing Alkemio links on LinkedIn I want that Alkemio shows up well
As a communications lead I want Alkemio to display well on LinkedIn

## Acceptance criteria

- [x] Client to add image as per feedback from https://www.linkedin.com/post-inspector
- [ ] Description field updated

## Additional Context
<img width="1571" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE51QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec02887ea1fbf02f26f28c9acba15fdb4d73c512/image.png" alt="image.png" />

**Comment by techsmyth** [comment]
@Fintokyo can you please suggest a description for the tagline on the foundation, which may well differ from that on the platform...

**Comment by keyboardguy25** [comment]
added meta tags in [PR #749](https://github.com/alkem-io/website/compare/meta-tags-foundation)

**Comment by techsmyth** [comment]
Thanks @bobbykolev - this issue can then be closed.

Quick question: where is the tagline being picked up from?

**Comment by bobbykolev** [comment]
Here's the final result @techsmyth . Note this was the website - alkemio.org. I'll make the same change for the welcome site shortly (I've missed that). The tagline is the meta description. If missing the script could display relevant information like the URL or snippet from the page.
<img width="446" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWZMQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77db9b9fe06d7b2cf7e53d49f8e2913befe9e37c/image.png" alt="image.png" />
