### ISSUE TITLE
BUG: "To the Platform" label doesn't fit within the button

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/website#740]
**Describe the bug**

**To Reproduce**

1. Go to https://welcome.acc-alkem.io/ "To the Platform" label doesn't fit within the button
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3lFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b9da1b85f30efc4294c1ad5b2037e2bbc0d866a/image.png" alt="image.png" />

**Expected behavior**
Label fits well within button.

**Comment by SimoneZaza** [comment]
@Comoque1 thanks for checking! @ccanos can you maybe have a look?
